// ── This file is auto-generated by @-label-/api-codegen ──
// Do NOT edit — it will be overwritten on regeneration.
// Configure the client at runtime via configureClient() in your app.

import Axios from "axios";
import type { AxiosError, AxiosInstance, AxiosRequestConfig, InternalAxiosRequestConfig } from "axios";

let instance: AxiosInstance = Axios.create();

export type RequestInterceptor = [
  onFulfilled?: ((config: InternalAxiosRequestConfig) => InternalAxiosRequestConfig | Promise<InternalAxiosRequestConfig>) | null,
  onRejected?: ((error: unknown) => unknown) | null,
];

export type ResponseInterceptor = [
  onFulfilled?: ((response: import("axios").AxiosResponse) => import("axios").AxiosResponse | Promise<import("axios").AxiosResponse>) | null,
  onRejected?: ((error: unknown) => unknown) | null,
];

export type ClientConfig = {
  baseURL?: string;
  headers?: Record<string, string>;
  interceptors?: {
    request?: RequestInterceptor[];
    response?: ResponseInterceptor[];
  };
};

export function configureClient(config: ClientConfig): void {
  instance = Axios.create({
    ...(config.baseURL != null ? { baseURL: config.baseURL } : {}),
    ...(config.headers != null ? { headers: config.headers } : {}),
  });
  if (config.interceptors?.request) {
    for (const interceptor of config.interceptors.request) {
      instance.interceptors.request.use(...interceptor);
    }
  }
  if (config.interceptors?.response) {
    for (const interceptor of config.interceptors.response) {
      instance.interceptors.response.use(...interceptor);
    }
  }
}

type LooseRequestConfig = Omit<AxiosRequestConfig, 'signal'> & { signal?: AbortSignal | undefined };

export const customInstance = <T>(
  config: LooseRequestConfig,
  options?: AxiosRequestConfig,
): Promise<T> => {
  const { signal, ...rest } = config;
  return instance({ ...rest, ...(signal != null ? { signal } : {}), ...options }).then(({ data }) => data);
};

export type ErrorType<Error> = AxiosError<Error>;
export type BodyType<BodyData> = BodyData;
