/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Fleet API
 * Fleet vehicle management API
 * OpenAPI spec version: 1.0.0
 */

export * from './listVehiclesParams';
export * from './vehicle';
export * from './vehiclePatch';
export * from './vehicleStatus';
export * from './vehicleType';
