/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Fleet API
 * Fleet vehicle management API
 * OpenAPI spec version: 1.0.0
 */
import type { VehicleStatus } from './vehicleStatus';
import type { VehicleType } from './vehicleType';

export type ListVehiclesParams = {
  status?: VehicleStatus;
  type?: VehicleType;
  search?: string;
};
