/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Fleet API
 * Fleet vehicle management API
 * OpenAPI spec version: 1.0.0
 */
import type { VehicleStatus } from './vehicleStatus';

export interface VehiclePatch {
  status?: VehicleStatus;
  notes?: string;
  km?: number;
}
