/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Fleet API
 * Fleet vehicle management API
 * OpenAPI spec version: 1.0.0
 */

export type VehicleStatus = (typeof VehicleStatus)[keyof typeof VehicleStatus];

export const VehicleStatus = {
  available: 'available',
  rented: 'rented',
  maintenance: 'maintenance',
  blocked: 'blocked',
} as const;
