/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Fleet API
 * Fleet vehicle management API
 * OpenAPI spec version: 1.0.0
 */
import type { VehicleStatus } from './vehicleStatus';
import type { VehicleType } from './vehicleType';

export interface Vehicle {
  id: string;
  plate: string;
  model: string;
  brand: string;
  type: VehicleType;
  year: number;
  status: VehicleStatus;
  km: number;
  lastServiceDate: string;
  notes: string;
}
