/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Fleet API
 * Fleet vehicle management API
 * OpenAPI spec version: 1.0.0
 */

export type VehicleType = (typeof VehicleType)[keyof typeof VehicleType];

export const VehicleType = {
  car: 'car',
  motorcycle: 'motorcycle',
  van: 'van',
} as const;
