/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Fleet API
 * Fleet vehicle management API
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { ListVehiclesParams, Vehicle, VehiclePatch } from '../model';

import { customInstance } from '../mutator/custom-instance';
import type { ErrorType, BodyType } from '../mutator/custom-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary List vehicles with optional filters
 */
export const listVehicles = (params?: ListVehiclesParams, options?: SecondParameter<typeof customInstance>, signal?: AbortSignal) => {
  return customInstance<Vehicle[]>({ url: `/api/vehicles`, method: 'GET', params, signal }, options);
};

export const getListVehiclesQueryKey = (params?: ListVehiclesParams) => {
  return [`/api/vehicles`, ...(params ? [params] : [])] as const;
};

export const getListVehiclesQueryOptions = <TData = Awaited<ReturnType<typeof listVehicles>>, TError = ErrorType<unknown>>(
  params?: ListVehiclesParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof listVehicles>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListVehiclesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listVehicles>>> = ({ signal }) => listVehicles(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof listVehicles>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type ListVehiclesQueryResult = NonNullable<Awaited<ReturnType<typeof listVehicles>>>;
export type ListVehiclesQueryError = ErrorType<unknown>;

/**
 * @summary List vehicles with optional filters
 */

export function useListVehicles<TData = Awaited<ReturnType<typeof listVehicles>>, TError = ErrorType<unknown>>(
  params?: ListVehiclesParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof listVehicles>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListVehiclesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get a vehicle by ID
 */
export const getVehicle = (id: string, options?: SecondParameter<typeof customInstance>, signal?: AbortSignal) => {
  return customInstance<Vehicle>({ url: `/api/vehicles/${id}`, method: 'GET', signal }, options);
};

export const getGetVehicleQueryKey = (id: string) => {
  return [`/api/vehicles/${id}`] as const;
};

export const getGetVehicleQueryOptions = <TData = Awaited<ReturnType<typeof getVehicle>>, TError = ErrorType<void>>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getVehicle>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetVehicleQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getVehicle>>> = ({ signal }) => getVehicle(id, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getVehicle>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetVehicleQueryResult = NonNullable<Awaited<ReturnType<typeof getVehicle>>>;
export type GetVehicleQueryError = ErrorType<void>;

/**
 * @summary Get a vehicle by ID
 */

export function useGetVehicle<TData = Awaited<ReturnType<typeof getVehicle>>, TError = ErrorType<void>>(
  id: string,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getVehicle>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetVehicleQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Partially update a vehicle
 */
export const patchVehicle = (
  id: string,
  vehiclePatch: BodyType<VehiclePatch>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Vehicle>(
    { url: `/api/vehicles/${id}`, method: 'PATCH', headers: { 'Content-Type': 'application/json' }, data: vehiclePatch, signal },
    options,
  );
};

export const getPatchVehicleMutationOptions = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof patchVehicle>>, TError, { id: string; data: BodyType<VehiclePatch> }, TContext>;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<Awaited<ReturnType<typeof patchVehicle>>, TError, { id: string; data: BodyType<VehiclePatch> }, TContext> => {
  const mutationKey = ['patchVehicle'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchVehicle>>, { id: string; data: BodyType<VehiclePatch> }> = props => {
    const { id, data } = props ?? {};

    return patchVehicle(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchVehicleMutationResult = NonNullable<Awaited<ReturnType<typeof patchVehicle>>>;
export type PatchVehicleMutationBody = BodyType<VehiclePatch>;
export type PatchVehicleMutationError = ErrorType<void>;

/**
 * @summary Partially update a vehicle
 */
export const usePatchVehicle = <TError = ErrorType<void>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof patchVehicle>>, TError, { id: string; data: BodyType<VehiclePatch> }, TContext>;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<Awaited<ReturnType<typeof patchVehicle>>, TError, { id: string; data: BodyType<VehiclePatch> }, TContext> => {
  return useMutation(getPatchVehicleMutationOptions(options));
};
