/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Fleet API
 * Fleet vehicle management API
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { Vehicle } from '../model';

export const getListVehiclesResponseMock = (): Vehicle[] => [
  {
    id: 'v-001',
    plate: 'AA-01-BB',
    model: 'Corsa',
    brand: 'Opel',
    type: 'car',
    year: 2022,
    status: 'available',
    km: 34500,
    lastServiceDate: '2025-11-15',
    notes: '',
  },
  {
    id: 'v-002',
    plate: 'CC-02-DD',
    model: '208',
    brand: 'Peugeot',
    type: 'car',
    year: 2023,
    status: 'rented',
    km: 18200,
    lastServiceDate: '2025-12-01',
    notes: '',
  },
  {
    id: 'v-003',
    plate: 'EE-03-FF',
    model: 'Clio',
    brand: 'Renault',
    type: 'car',
    year: 2021,
    status: 'maintenance',
    km: 62000,
    lastServiceDate: '2025-10-20',
    notes: 'Brake pads replacement',
  },
  {
    id: 'v-004',
    plate: 'GG-04-HH',
    model: 'Duster',
    brand: 'Dacia',
    type: 'car',
    year: 2023,
    status: 'available',
    km: 12800,
    lastServiceDate: '2026-01-10',
    notes: '',
  },
  {
    id: 'v-005',
    plate: 'II-05-JJ',
    model: 'PCX 125',
    brand: 'Honda',
    type: 'motorcycle',
    year: 2024,
    status: 'available',
    km: 5600,
    lastServiceDate: '2026-01-20',
    notes: '',
  },
  {
    id: 'v-006',
    plate: 'KK-06-LL',
    model: 'Trafic',
    brand: 'Renault',
    type: 'van',
    year: 2020,
    status: 'blocked',
    km: 95000,
    lastServiceDate: '2025-09-01',
    notes: 'Insurance expired',
  },
  {
    id: 'v-007',
    plate: 'MM-07-NN',
    model: 'Yaris',
    brand: 'Toyota',
    type: 'car',
    year: 2024,
    status: 'available',
    km: 8200,
    lastServiceDate: '2026-02-01',
    notes: '',
  },
  {
    id: 'v-008',
    plate: 'OO-08-PP',
    model: 'Nmax 125',
    brand: 'Yamaha',
    type: 'motorcycle',
    year: 2023,
    status: 'rented',
    km: 11400,
    lastServiceDate: '2025-12-15',
    notes: '',
  },
  {
    id: 'v-009',
    plate: 'QQ-09-RR',
    model: 'Berlingo',
    brand: 'Citroën',
    type: 'van',
    year: 2022,
    status: 'available',
    km: 42000,
    lastServiceDate: '2025-11-20',
    notes: '',
  },
  {
    id: 'v-010',
    plate: 'SS-10-TT',
    model: 'Ibiza',
    brand: 'Seat',
    type: 'car',
    year: 2021,
    status: 'available',
    km: 55000,
    lastServiceDate: '2025-10-01',
    notes: '',
  },
  {
    id: 'v-011',
    plate: 'UU-11-VV',
    model: 'T-Cross',
    brand: 'Volkswagen',
    type: 'car',
    year: 2023,
    status: 'maintenance',
    km: 28000,
    lastServiceDate: '2026-02-10',
    notes: 'Oil change',
  },
  {
    id: 'v-012',
    plate: 'WW-12-XX',
    model: 'SH 125',
    brand: 'Honda',
    type: 'motorcycle',
    year: 2022,
    status: 'available',
    km: 15600,
    lastServiceDate: '2025-12-20',
    notes: '',
  },
];

/**
 * @mock **deterministic** — uses `example` values from the OpenAPI spec.
 * Safe to use in tests without overrides.
 */
export const getGetVehicleResponseMock = (): Vehicle => ({
  id: 'v-001',
  plate: 'AA-01-BB',
  model: 'Corsa',
  brand: 'Opel',
  type: 'car',
  year: 2022,
  status: 'available',
  km: 34500,
  lastServiceDate: '2025-11-15',
  notes: '',
});

/**
 * @mock **deterministic** — uses `example` values from the OpenAPI spec.
 * Safe to use in tests without overrides.
 */
export const getPatchVehicleResponseMock = (): Vehicle => ({
  id: 'v-001',
  plate: 'AA-01-BB',
  model: 'Corsa',
  brand: 'Opel',
  type: 'car',
  year: 2022,
  status: 'blocked',
  km: 34500,
  lastServiceDate: '2025-11-15',
  notes: 'Status updated',
});

export const getListVehiclesMockHandler = (
  overrideResponse?: Vehicle[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Vehicle[]> | Vehicle[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/vehicles',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getListVehiclesResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetVehicleMockHandler = (
  overrideResponse?: Vehicle | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Vehicle> | Vehicle),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/vehicles/:id',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetVehicleResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPatchVehicleMockHandler = (
  overrideResponse?: Vehicle | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Vehicle> | Vehicle),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    '*/api/vehicles/:id',
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchVehicleResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getFleetAPIMock = () => [getListVehiclesMockHandler(), getGetVehicleMockHandler(), getPatchVehicleMockHandler()];
